---
# https://circleci.com/docs/docker
version: 2
jobs:
    build:
        docker:
            # https://github.com/jumanjihouse/cci/pulls?q=is%3Apr+is%3Aclosed
            - image: jumanjiman/cci:20220712.1639

        working_directory: ~/workdir/

        steps:
            - setup_remote_docker
            - checkout
            - run:
                  name: Bootstrap the local environment
                  command: ci/bootstrap
            - run:
                  name: Build project
                  command: ci/build
            - run:
                  name: Run tests
                  command: ci/test
